### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: 6pOYgE5769efeb2c40647108RVcQOco0

origin=64999&destination=64942&weight=1000&courier=jne